import { AiFillLock, AiOutlineMail } from "react-icons/ai";

const registerInput = [
  {
    icon: AiOutlineMail,
    type: "text",
    name: "first_name",
    id: "first_name",
    placeholder: "Enter your First Name",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 0,
  },
  {
    icon: AiOutlineMail,
    type: "text",
    name: "last_name",
    id: "last_name",
    placeholder: "Enter your Last Name",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 1,
  },
  {
    icon: AiOutlineMail,
    type: "text",
    name: "username",
    id: "username",
    placeholder: "Enter your Name",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 2,
  },
  {
    icon: AiOutlineMail,
    type: "text",
    name: "email",
    id: "email",
    placeholder: "Enter your Email",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 3,
  },
  {
    icon: AiOutlineMail,
    type: "text",
    name: "mobile",
    id: "mobile",
    placeholder: "Enter your Mobile",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 4,
  },
  {
    icon: AiFillLock,
    type: "password",
    name: "password",
    id: "password",
    placeholder: "●●●●●●●●●●",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 5,
  },
  {
    icon: AiFillLock,
    type: "password",
    name: "password_confirmation",
    id: "password_confirmation",
    placeholder: "●●●●●●●●●●",
    onchange: () => {},
    className: "bg-gray-900 border-solid text-white",
    submit: false,
    validate: false,
    errorMessage: "",
    key: 6,
  },
];

export default registerInput;
